Modified index and script to use fetch() to request content from server
thuavu/my-portfolio pull request #5
Opened 2020-06-14 05:13 UTC by thuavu

2020-06-14 17:56 UTC, TsueiCat requested changes
Nice work! Could you also include a screenshot of this change (how your portfolio looks when you click on the button) to the description?

2020-06-14 17:56 UTC, TsueiCat commented on portfolio/src/main/webapp/index.html
> +            <!--<a href="/data"><button class="buttonBox"><h3>Comments</h3></button></a>-->
Remove commented-out line.

2020-06-14 21:27 UTC, thuavu commented
![image](https://user-images.githubusercontent.com/44590322/84604359-fa6da200-ae5a-11ea-9e30-1c67cfa89881.png)
![image](https://user-images.githubusercontent.com/44590322/84604362-0c4f4500-ae5b-11ea-8769-3540d18c2f59.png)
@TsueiCat 
The button essentially request go to the /data page which fetch content from the server and add it to a HTML page.

2020-06-15 04:06 UTC, TsueiCat requested changes
Please also resolve comments made! :)

2020-06-15 04:08 UTC, thuavu commented
I think I got them now

2020-06-15 04:23 UTC, TsueiCat reviewed
Please add the commit change to this PR!

2020-06-15 04:45 UTC, thuavu commented
@TsueiCat I sent the commit accidentally to the other branch.

2020-06-15 05:01 UTC, TsueiCat reviewed
Just add another commit to this branch that contains the change :) When you merge this branch to master, before merging the other pull request you'll want to run 'git pull origin master' to get the latest copy and the commit you made there for this PR will have no diff in code changes (for removing the commented-out line).

2020-06-15 05:19 UTC, thuavu commented
@TsueiCat I'm currently getting a merge conflict

2020-06-15 06:59 UTC, TsueiCat approved these changes
Good job sorting out problems yourself! 😸

2020-06-15 07:02 UTC, thuavu commented
@TsueiCat Haha, it was mainly just trying different things until they work.

2020-06-15 07:02 UTC, merged